<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Real Time Currency Convertor</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="currencyConv.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  </head>
  <body>

    <div class="jumbotron h1">
      <h1 class="cen">Real Time Currency Convertor</h1>
    </div>
    <form class="" action="currencyConv.php" method="POST">
    <div class="div1">
      <br>
      <div class="cen container">
        FROM:<select name="from" required >
        <option value='XCD'>Anguilla(East Caribbean Dollar)</option>
        <option value='ARS'>Argentina(Argentine Peso)</option>
        <option value='AWG'>Aruba(Aruban Florin)</option>
        <option value='AUD'>Australia(Australian Dollar)</option>
        <option value='AZN'>Azerbaijan(Azerbaijan Manat)</option>
        <option value='BSD'>Bahamas(Bahamian Dollar)</option>
        <option value='BHD'>Bahrain(Bahraini Dinar)</option>
        <option value='BDT'>Bangladesh(Bangladeshi Taka)</option>
        <option value='BBD'>Barbados(Barbados Dollar)</option>
        <option value='BYR'>Belarus(Belarusian Ruble)</option>
        <option value='BZD'>Belize(Belize Dollar)</option>
        <option value='XOF'>Benin(CFA Franc BCEAO)</option>
        <option value='BMD'>Bermuda(Bermudian Dollar)</option>
        <option value='BAM'>Bosnia and Herzegovina(Mark)</option>
        <option value='BWP'>Botswana(Pula)</option>
        <option value='BRL'>Brazil(Brazilian Real)</option>
        <option value='BND'>Brunei Darussalam(Brunei Dollar)</option>
        <option value='BGN'>Bulgaria(Bulgarian Lev)</option>
        <option value='XOF'>Burkina Faso(CFA Franc BCEAO)</option>
        <option value='BIF'>Burundi(Burundi Franc)</option>
        <option value='KHR'>Cambodia(Cambodian Riel)</option>
        <option value='XAF'>Cameroon(CFA Franc BEAC)</option>
        <option value='CAD'>Canada(Canadian Dollar)</option>
        <option value='CVE'>Cape Verde(Cape Verde Escudo)</option>
        <option value='KYD'>Cayman Islands(Cayman Islands Dollar)</option>
        <option value='XAF'>Central African Republic(CFA Franc BEAC)</option>
        <option value='XAF'>Chad(CFA Franc BEAC)</option>
        <option value='CLP'>Chile(Chilean Peso)</option>
        <option value='CNY'>China( Renminbi (Yuan))</option>
        <option value='AUD'>Christmas Island(Australian Dollar)</option>
        <option value='AUD'>Cocos Islands(Australian Dollar)</option>
        <option value='COP'>Colombia(Colombian Peso)</option>
        <option value='KMF'>Comoros(Comoro Franc)</option>
        <option value='CDF'>Congo, Dem. Republic(Franc Congolais)</option>
        <option value='NZD'>Cook Islands(New Zealand Dollar)</option>
        <option value='XOF'>Cote D'Ivoire(CFA Franc BCEAO)</option>
        <option value='CUP'>Cuba(Cuban Peso)</option>
        <option value='CZK'>Czech Republic(Czech Koruna)</option>
        <option value='DKK'>Denmark(Danish Kroner)</option>
        <option value='DJF'>Djibouti(Djibouti Franc)</option>
        <option value='XCD'>Dominica(East Caribbean Dollar)</option>
        <option value='DOP'>Dominican Republic(Dominican Peso)</option>
        <option value='USD'>Ecuador(US Dollar)</option>
        <option value='EGP'>Egypt(Egyptian Pound)</option>
        <option value='ERN'>Eritrea(Nakfa)</option>
        <option value='EEK'>Estonia(Euro</option>
        <option value='ETB'>Ethiopia(Ethiopian Birr)</option>
        <option value='FKP'>Falkland Islands(Falkland Islands pound)</option>
        <option value='FOK'>Faroe Islands(Faroese króna)</option>
        <option value='FJD'>Fiji(Fiji Dollar)</option>
        <option value='CFP'>France(CFP franc)</option>
        <option value='XAF'>Gabon(CFA Franc BEAC)</option>
        <option value='GMD'>Gambia(Dalasi)</option>
        <option value='GEL'>Georgia(Lari)</option>
        <option value='GHC'>Ghana(Cedi)</option>
        <option value='GIP'>Gibraltar(Gibraltar Pound)</option>
        <option value='DKK'>Greenland(Danish Krone)</option>
        <option value='XCD'>Grenada(East Caribbean Dollar)</option>
        <option value='EUR'>Guadeloupe(Euro)</option>
        <option value='USD'>Guam(US Dollar)</option>
        <option value='GTQ'>Guatemala(Quetzal)</option>
        <option value='GNF'>Guinea(Guinea Franc)</option>
        <option value='GYD'>Guyana(Guyana Dollar)</option>
        <option value='HNL'>Honduras(Lempira)</option>
        <option value='HKD'>Hong Kong(Hong Kong Dollar)</option>
        <option value='HUF'>Hungary(Forint)</option>
        <option value='ISK'>Iceland(Iceland Krona)</option>
        <option value='INR'>India(Indian Rupee)</option>
        <option value='IDR'>Indonesia(Rupiah)</option>
        <option value='IRR'>Iran(Iranian Rial)</option>
        <option value='IQD'>Iraq(Iraqi Dinar)</option>
        <option value='ILS'>Israel(New Israeli Sheqel)</option>
        <option value='JMD'>Jamaica(Jamaican Dollar)</option>
        <option value='JPY'>Japan(Yen)</option>
        <option value='JOD'>Jordan(Jordanian Dinar)</option>
        <option value='KZT'>Kazakhstan(Tenge)</option>
        <option value='KES'>Kenya(Kenyan Shilling)</option>
        <option value='AUD'>Kiribati(Australian Dollar)</option>
        <option value='KPW'>North Korea(North Korean Won)</option>
        <option value='KRW'>South Korea(Won)</option>
        <option value='KWD'>Kuwait(Kuwaiti Dinar)</option>
        <option value='KGS'>Kyrgyzstan(Som)</option>
        <option value='LAK'>Lao(Kip)</option>
        <option value='EUR'>Latvia(Euro)</option>
        <option value='LBP'>Lebanon(Lebanese Pound)</option>
        <option value='LSL'>Lesotho(Loti )</option>
        <option value='LRD'>Liberia(Liberian Dollar)</option>
        <option value='LYD'>Libya(Lybian Dinar)</option>
        <option value='CHF'>Liechtenstein(Swiss Franc)</option>
        <option value='LTL'>Lithuania(Euro)</option>
        <option value='MOP'>Macau(Macanese Pataca )</option>
        <option value='MKD'>Macedonia(Macedonian Denar)</option>
        <option value='MGF'>Madagascar(Malagasy Franc)</option>
        <option value='MWK'>Malawi(Kwacha)</option>
        <option value='MYR'>Malaysia(Malaysian Ringgit)</option>
        <option value='MVR'>Maldives(Rufiyaa)</option>
        <option value='XOF'>Mali(CFA Franc BCEAO)</option>
        <option value='MTL'>Malta(Maltese Lira)</option>
        <option value='USD'>Marshall Islands(US Dollar)</option>
        <option value='EUR'>Martinique(Euro)</option>
        <option value='MRO'>Mauritania(Ouguiya)</option>
        <option value='MUR'>Mauritius(Mauritius Rupee)</option>
        <option value='EUR'>Mayotte (DROM France)(Euro)</option>
        <option value='MDL'>Moldova, Republic of(Moldovan Leu)</option>
        <option value='EUR'>Monaco(Euro)</option>
        <option value='MNT'>Mongolia(Mongolia Tughrik)</option>
        <option value='EUR'> Montenegro(Euro)</option>
        <option value='XCD'>Montserrat(East Caribbean Dollar)</option>
        <option value='MAD'>Morocco(Moroccan Dirham)</option>
        <option value='MZM'>Mozambique(Mozambican Metical)</option>
        <option value='MMK'>Myanmar(Burmese Kyat)</option>
        <option value='AUD'>Nauru(Australian Dollar)</option>
        <option value='NPR'>Nepal(Nepalese Rupee)</option>
        <option value='ANG'>Netherland(Netherlands Antilles Guilder)</option>
        <option value='XPF'>New Caledonia(CFP Franc)</option>
        <option value='NZD'>New Zealand(New Zealand Dollar)</option>
        <option value='NIO'>Nicaragua(Nicaraguan Córdoba)</option>
        <option value='XOF'>Niger(West African CFA Franc)</option>
        <option value='NGN'>Nigeria(Nigerian Naira)</option>
        <option value='NZD'>Niue(New Zealand Dollar)</option>
        <option value='USD'>Northern Mariana Islands(US Dollar)</option>
        <option value='NOK'>Norway(Norwegian Krone)</option>
        <option value='OMR'>Oman(Omani Rial)</option>
        <option value='PKR'>Pakistan(Pakistan Rupee)</option>
        <option value='USD'>Palau(US Dollar)</option>
        <option value='PGK'>Papua New Guinea(Papua New Guinean Kina)</option>
        <option value='PYG'>Paraguay(Paraguayan Guarani)</option>
        <option value='PEN'>Peru(Peruvian (Nuevo) Sol)</option>
        <option value='PHP'>Philippines(Philippine Peso)</option>
        <option value='NZD'>Pitcairn Island(New Zealand Dollar)</option>
        <option value='PLN'>Poland(Polish Zloty (złoty))</option>
        <option value='USD'>Puerto Rico(US Dollar)</option>
        <option value='QAR'>Qatar(Qatari Rial)</option>
        <option value='EUR'>Reunion Island(Euro)</option>
        <option value='ROL'>Romania(Leu)</option>
        <option value='RWF'>Rwanda(Rwanda Franc)</option>
        <option value='SHP'>Saint Helena(Saint Helena Pound)</option>
        <option value='XCD'>Saint Lucia(East Caribbean Dollar)</option>
        <option value='WST'>Samoa(Tala)</option>
        <option value='EUR'>San Marino(Euro)</option>
        <option value='STD'>Sao Tome and Principe(Dobra)</option>
        <option value='SAR'>Saudi Arabia(Saudi Riyal)</option>
        <option value='XOF'>Senegal(CFA Franc BCEAO)</option>
        <option value='SCR'>Seychelles(Seychelles Rupee)</option>
        <option value='SLL'>Sierra Leone(Leone)</option>
        <option value='SGD'>Singapore(Singapore Dollar)</option>
        <option value='SBD'>Solomon Islands(Solomon Islands Dollar)</option>
        <option value='SOS'>Somalia(Somali Shilling)</option>
        <option value='ZAR'>South Africa(Rand)</option>
        <option value='LKR'>Sri Lanka(Sri Lanka Rupee)</option>
        <option value='SRG'>Suriname(Suriname Guilder)</option>
        <option value='SZL'>Swaziland(Lilangeni)</option>
        <option value='SEK'>Sweden(Swedish Krona)</option>
        <option value='CHF'>Switzerland(Swiss Franc)</option>
        <option value='SYP'>Syrian Arab Republic(Syrian Pound)</option>
        <option value='TWD'>Taiwan</option>
        <option value='TJS'>Tajikistan(Somoni)</option>
        <option value='TZS'>Tanzania(Tanzanian Shilling)</option>
        <option value='THB'>Thailand(Thai Baht)</option>
        <option value='USD'>Timor Leste(US Dollar)</option>
        <option value='XOF'>Togo(CFA Franc BCEAO)</option>
        <option value='NZD'>Tokelau(New Zealand Dollar)</option>
        <option value='TOP'>Tonga(Paʻanga)</option>
        <option value='TTD'>Trinidad and Tobago(T&T Dollar)</option>
        <option value='TND'>Tunisia(Tunisian Dinar)</option>
        <option value='TRY'>Turkey(Turkish lira)</option>
        <option value='TMM'>Turkmenistan(Manat)</option>
        <option value='USD'>Turks and Caicos Islands(US Dollar)</option>
        <option value='AUD'>Tuvalu(Australian Dollar)</option>
        <option value='UGX'>Uganda(Uganda Shilling)</option>
        <option value='UAH'>Ukraine(Ukrainian Hryvnia)</option>
        <option value='AED'>United Arab Emirates(UAE Dirham)</option>
        <option value='GBP'>United Kingdom(Pound Sterling)</option>
        <option value='USD'>United States of America(US Dollar)</option>
        <option value='UYU'>Uruguay(Uruguayan Peso)</option>
        <option value='UZS'>Uzbekistan(Uzbekistan Sum)</option>
        <option value='VUV'>Vanuatu(Vanuatu Vatu)</option>
        <option value='VND'>Vietnam(Vietnamese Dong)</option>
        <option value='XPF'>Wallis and Futuna Islands(CFP Franc)</option>
        <option value='MAD'>Western Sahara(Moroccan Dirham)</option>
        <option value='YER'>Yemen(Yemeni Rial)</option>
        <option value='ZMW'>Zambia(Zambian Kwacha)</option>
        <option value='ZWD'>Zimbabwe(Zimbabwe Dollar)</option>
        </select>

        TO:<select name="to" >
          <option value='XCD'>Anguilla(East Caribbean Dollar)</option>
          <option value='ARS'>Argentina(Argentine Peso)</option>
          <option value='AWG'>Aruba(Aruban Florin)</option>
          <option value='AUD'>Australia(Australian Dollar)</option>
          <option value='AZN'>Azerbaijan(Azerbaijan Manat)</option>
          <option value='BSD'>Bahamas(Bahamian Dollar)</option>
          <option value='BHD'>Bahrain(Bahraini Dinar)</option>
          <option value='BDT'>Bangladesh(Bangladeshi Taka)</option>
          <option value='BBD'>Barbados(Barbados Dollar)</option>
          <option value='BYR'>Belarus(Belarusian Ruble)</option>
          <option value='BZD'>Belize(Belize Dollar)</option>
          <option value='XOF'>Benin(CFA Franc BCEAO)</option>
          <option value='BMD'>Bermuda(Bermudian Dollar)</option>
          <option value='BAM'>Bosnia and Herzegovina(Mark)</option>
          <option value='BWP'>Botswana(Pula)</option>
          <option value='BRL'>Brazil(Brazilian Real)</option>
          <option value='BND'>Brunei Darussalam(Brunei Dollar)</option>
          <option value='BGN'>Bulgaria(Bulgarian Lev)</option>
          <option value='XOF'>Burkina Faso(CFA Franc BCEAO)</option>
          <option value='BIF'>Burundi(Burundi Franc)</option>
          <option value='KHR'>Cambodia(Cambodian Riel)</option>
          <option value='XAF'>Cameroon(CFA Franc BEAC)</option>
          <option value='CAD'>Canada(Canadian Dollar)</option>
          <option value='CVE'>Cape Verde(Cape Verde Escudo)</option>
          <option value='KYD'>Cayman Islands(Cayman Islands Dollar)</option>
          <option value='XAF'>Central African Republic(CFA Franc BEAC)</option>
          <option value='XAF'>Chad(CFA Franc BEAC)</option>
          <option value='CLP'>Chile(Chilean Peso)</option>
          <option value='CNY'>China( Renminbi (Yuan))</option>
          <option value='AUD'>Christmas Island(Australian Dollar)</option>
          <option value='AUD'>Cocos Islands(Australian Dollar)</option>
          <option value='COP'>Colombia(Colombian Peso)</option>
          <option value='KMF'>Comoros(Comoro Franc)</option>
          <option value='CDF'>Congo, Dem. Republic(Franc Congolais)</option>
          <option value='NZD'>Cook Islands(New Zealand Dollar)</option>
          <option value='XOF'>Cote D'Ivoire(CFA Franc BCEAO)</option>
          <option value='CUP'>Cuba(Cuban Peso)</option>
          <option value='CZK'>Czech Republic(Czech Koruna)</option>
          <option value='DKK'>Denmark(Danish Kroner)</option>
          <option value='DJF'>Djibouti(Djibouti Franc)</option>
          <option value='XCD'>Dominica(East Caribbean Dollar)</option>
          <option value='DOP'>Dominican Republic(Dominican Peso)</option>
          <option value='USD'>Ecuador(US Dollar)</option>
          <option value='EGP'>Egypt(Egyptian Pound)</option>
          <option value='ERN'>Eritrea(Nakfa)</option>
          <option value='EEK'>Estonia(Euro</option>
          <option value='ETB'>Ethiopia(Ethiopian Birr)</option>
          <option value='FKP'>Falkland Islands(Falkland Islands pound)</option>
          <option value='FOK'>Faroe Islands(Faroese króna)</option>
          <option value='FJD'>Fiji(Fiji Dollar)</option>
          <option value='CFP'>France(CFP franc)</option>
          <option value='XAF'>Gabon(CFA Franc BEAC)</option>
          <option value='GMD'>Gambia(Dalasi)</option>
          <option value='GEL'>Georgia(Lari)</option>
          <option value='GHC'>Ghana(Cedi)</option>
          <option value='GIP'>Gibraltar(Gibraltar Pound)</option>
          <option value='DKK'>Greenland(Danish Krone)</option>
          <option value='XCD'>Grenada(East Caribbean Dollar)</option>
          <option value='EUR'>Guadeloupe(Euro)</option>
          <option value='USD'>Guam(US Dollar)</option>
          <option value='GTQ'>Guatemala(Quetzal)</option>
          <option value='GNF'>Guinea(Guinea Franc)</option>
          <option value='GYD'>Guyana(Guyana Dollar)</option>
          <option value='HNL'>Honduras(Lempira)</option>
          <option value='HKD'>Hong Kong(Hong Kong Dollar)</option>
          <option value='HUF'>Hungary(Forint)</option>
          <option value='ISK'>Iceland(Iceland Krona)</option>
          <option value='INR'>India(Indian Rupee)</option>
          <option value='IDR'>Indonesia(Rupiah)</option>
          <option value='IRR'>Iran(Iranian Rial)</option>
          <option value='IQD'>Iraq(Iraqi Dinar)</option>
          <option value='ILS'>Israel(New Israeli Sheqel)</option>
          <option value='JMD'>Jamaica(Jamaican Dollar)</option>
          <option value='JPY'>Japan(Yen)</option>
          <option value='JOD'>Jordan(Jordanian Dinar)</option>
          <option value='KZT'>Kazakhstan(Tenge)</option>
          <option value='KES'>Kenya(Kenyan Shilling)</option>
          <option value='AUD'>Kiribati(Australian Dollar)</option>
          <option value='KPW'>North Korea(North Korean Won)</option>
          <option value='KRW'>South Korea(Won)</option>
          <option value='KWD'>Kuwait(Kuwaiti Dinar)</option>
          <option value='KGS'>Kyrgyzstan(Som)</option>
          <option value='LAK'>Lao(Kip)</option>
          <option value='EUR'>Latvia(Euro)</option>
          <option value='LBP'>Lebanon(Lebanese Pound)</option>
          <option value='LSL'>Lesotho(Loti )</option>
          <option value='LRD'>Liberia(Liberian Dollar)</option>
          <option value='LYD'>Libya(Lybian Dinar)</option>
          <option value='CHF'>Liechtenstein(Swiss Franc)</option>
          <option value='LTL'>Lithuania(Euro)</option>
          <option value='MOP'>Macau(Macanese Pataca )</option>
          <option value='MKD'>Macedonia(Macedonian Denar)</option>
          <option value='MGF'>Madagascar(Malagasy Franc)</option>
          <option value='MWK'>Malawi(Kwacha)</option>
          <option value='MYR'>Malaysia(Malaysian Ringgit)</option>
          <option value='MVR'>Maldives(Rufiyaa)</option>
          <option value='XOF'>Mali(CFA Franc BCEAO)</option>
          <option value='MTL'>Malta(Maltese Lira)</option>
          <option value='USD'>Marshall Islands(US Dollar)</option>
          <option value='EUR'>Martinique(Euro)</option>
          <option value='MRO'>Mauritania(Ouguiya)</option>
          <option value='MUR'>Mauritius(Mauritius Rupee)</option>
          <option value='EUR'>Mayotte (DROM France)(Euro)</option>
          <option value='MDL'>Moldova, Republic of(Moldovan Leu)</option>
          <option value='EUR'>Monaco(Euro)</option>
          <option value='MNT'>Mongolia(Mongolia Tughrik)</option>
          <option value='EUR'> Montenegro(Euro)</option>
          <option value='XCD'>Montserrat(East Caribbean Dollar)</option>
          <option value='MAD'>Morocco(Moroccan Dirham)</option>
          <option value='MZM'>Mozambique(Mozambican Metical)</option>
          <option value='MMK'>Myanmar(Burmese Kyat)</option>
          <option value='AUD'>Nauru(Australian Dollar)</option>
          <option value='NPR'>Nepal(Nepalese Rupee)</option>
          <option value='ANG'>Netherland(Netherlands Antilles Guilder)</option>
          <option value='XPF'>New Caledonia(CFP Franc)</option>
          <option value='NZD'>New Zealand(New Zealand Dollar)</option>
          <option value='NIO'>Nicaragua(Nicaraguan Córdoba)</option>
          <option value='XOF'>Niger(West African CFA Franc)</option>
          <option value='NGN'>Nigeria(Nigerian Naira)</option>
          <option value='NZD'>Niue(New Zealand Dollar)</option>
          <option value='USD'>Northern Mariana Islands(US Dollar)</option>
          <option value='NOK'>Norway(Norwegian Krone)</option>
          <option value='OMR'>Oman(Omani Rial)</option>
          <option value='PKR'>Pakistan(Pakistan Rupee)</option>
          <option value='USD'>Palau(US Dollar)</option>
          <option value='PGK'>Papua New Guinea(Papua New Guinean Kina)</option>
          <option value='PYG'>Paraguay(Paraguayan Guarani)</option>
          <option value='PEN'>Peru(Peruvian (Nuevo) Sol)</option>
          <option value='PHP'>Philippines(Philippine Peso)</option>
          <option value='NZD'>Pitcairn Island(New Zealand Dollar)</option>
          <option value='PLN'>Poland(Polish Zloty (złoty))</option>
          <option value='USD'>Puerto Rico(US Dollar)</option>
          <option value='QAR'>Qatar(Qatari Rial)</option>
          <option value='EUR'>Reunion Island(Euro)</option>
          <option value='ROL'>Romania(Leu)</option>
          <option value='RWF'>Rwanda(Rwanda Franc)</option>
          <option value='SHP'>Saint Helena(Saint Helena Pound)</option>
          <option value='XCD'>Saint Lucia(East Caribbean Dollar)</option>
          <option value='WST'>Samoa(Tala)</option>
          <option value='EUR'>San Marino(Euro)</option>
          <option value='STD'>Sao Tome and Principe(Dobra)</option>
          <option value='SAR'>Saudi Arabia(Saudi Riyal)</option>
          <option value='XOF'>Senegal(CFA Franc BCEAO)</option>
          <option value='SCR'>Seychelles(Seychelles Rupee)</option>
          <option value='SLL'>Sierra Leone(Leone)</option>
          <option value='SGD'>Singapore(Singapore Dollar)</option>
          <option value='SBD'>Solomon Islands(Solomon Islands Dollar)</option>
          <option value='SOS'>Somalia(Somali Shilling)</option>
          <option value='ZAR'>South Africa(Rand)</option>
          <option value='LKR'>Sri Lanka(Sri Lanka Rupee)</option>
          <option value='SRG'>Suriname(Suriname Guilder)</option>
          <option value='SZL'>Swaziland(Lilangeni)</option>
          <option value='SEK'>Sweden(Swedish Krona)</option>
          <option value='CHF'>Switzerland(Swiss Franc)</option>
          <option value='SYP'>Syrian Arab Republic(Syrian Pound)</option>
          <option value='TWD'>Taiwan(New Taiwan Dollar)</option>
          <option value='TJS'>Tajikistan(Somoni)</option>
          <option value='TZS'>Tanzania(Tanzanian Shilling)</option>
          <option value='THB'>Thailand(Thai Baht)</option>
          <option value='USD'>Timor Leste(US Dollar)</option>
          <option value='XOF'>Togo(CFA Franc BCEAO)</option>
          <option value='NZD'>Tokelau(New Zealand Dollar)</option>
          <option value='TOP'>Tonga(Paʻanga)</option>
          <option value='TTD'>Trinidad and Tobago(T&T Dollar)</option>
          <option value='TND'>Tunisia(Tunisian Dinar)</option>
          <option value='TRY'>Turkey(Turkish lira)</option>
          <option value='TMM'>Turkmenistan(Manat)</option>
          <option value='USD'>Turks and Caicos Islands(US Dollar)</option>
          <option value='AUD'>Tuvalu(Australian Dollar)</option>
          <option value='UGX'>Uganda(Uganda Shilling)</option>
          <option value='UAH'>Ukraine(Ukrainian Hryvnia)</option>
          <option value='AED'>United Arab Emirates(UAE Dirham)</option>
          <option value='GBP'>United Kingdom(Pound Sterling)</option>
          <option value='USD'>United States of America(US Dollar)</option>
          <option value='UYU'>Uruguay(Uruguayan Peso)</option>
          <option value='UZS'>Uzbekistan(Uzbekistan Sum)</option>
          <option value='VUV'>Vanuatu(Vanuatu Vatu)</option>
          <option value='VND'>Vietnam(Vietnamese Dong)</option>
          <option value='XPF'>Wallis and Futuna Islands(CFP Franc)</option>
          <option value='MAD'>Western Sahara(Moroccan Dirham)</option>
          <option value='YER'>Yemen(Yemeni Rial)</option>
          <option value='ZMW'>Zambia(Zambian Kwacha)</option>
          <option value='ZWD'>Zimbabwe(Zimbabwe Dollar)</option>
    </select>
    <br>
      </div>
      <div class="cen">
        <br>
      VALUE :<input type="number" name="val" min="1" value="1" class="size cen">
      </div>
      <br>
      <div class="cen">
          <button type="submit" name="sub" id="button" >SUBMIT</button>
          <br><br>
      </div>
    </div>
    </form>
    <?php
    if(isset($_POST['sub']))
    {
      $frm = $_POST['from'];
      $to = $_POST['to'];
      $value = $_POST['val'];
      $output = exec("python C:\Users\Gautham\Desktop\curr.py $value $frm $to");
      echo "<br><h1 class='cen jumbotron h1'>$value $frm =  $output $to</h1>";
    }
     ?>

  </body>
</html>
